name: Run Tests

on: [push, pull_request]

jobs:

  test:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
      with:
          submodules: true
  
    - name: Install required PHP version
      uses: shivammathur/setup-php@v1
      with:
          php-version: '7.3' #This version is currently used by Symcon | In later versions the tested wddx function is removed

    - name: Install latest PHPUnit
      run: wget https://phar.phpunit.de/phpunit.phar

    - name: Run Tests
      run: phpdbg -qrr phpunit.phar tests --configuration tests/phpunit.xml